"""MetaEvidence: reproducible evidence retrieval for systematic reviews."""

from .models import EvidenceRecord, SourceHit
from .query import (
    Boolean,
    ControlledVocabulary,
    Field,
    Not,
    Phrase,
    Proximity,
    QueryNode,
    QueryParser,
    QuerySyntaxError,
    SearchField,
    SearchQuery,
    Term,
    parse_query,
    render,
)
from .pico import ConceptBlock, PICOBuilder, PECOBuilder
from .dedup import (
    ConfidenceDeduplicationEngine,
    DeduplicationDecision,
    DeduplicationEngine,
    DeduplicationResult,
    DeduplicationStats,
    DuplicateLink,
    EvidenceContribution,
    MatchAssessment,
    MatchFeatures,
)
from .benchmark import (
    BenchmarkMetrics,
    DeduplicationBenchmark,
    LabeledPair,
    PlattCalibrator,
    ThresholdResult,
)
from .study_linkage import (
    DoubleCountingRisk,
    PublicationRole,
    StudyEvidenceContribution,
    StudyFamily,
    StudyLinkAssessment,
    StudyLinkDecision,
    StudyLinkFeatures,
    StudyLinkageEngine,
    StudyLinkageResult,
    StudyLinkageStats,
    classify_publication_role,
    extract_registry_ids,
    extract_study_acronyms,
)
from .study_benchmark import (
    StudyLabeledPair,
    StudyLinkageBenchmark,
    StudyLinkageMetrics,
    StudyThresholdResult,
)
from .ids import stable_record_id
from .screening import (
    DEFAULT_EXCLUSION_REASONS,
    ExclusionReason,
    ReasonCodebook,
    ScreeningConflict,
    ScreeningDecision,
    ScreeningEvent,
    ScreeningLedger,
    ScreeningStage,
    ReviewerAgreement,
)
from .interoperability import (
    ImportResult,
    ImportWarning,
    read_csv,
    read_ris,
    record_to_row,
    write_asreview_csv,
    write_bibtex,
    write_csv,
    write_jsonl,
    write_ris,
    write_screening_bundle,
)
from .manifest import SearchManifest
from .http import DiskResponseCache, RawAuditStore, RetryPolicy, RequestLogEntry, HTTPRequestError
from .adapters import (
    AdapterResult,
    PubMedAdapter,
    OpenAlexAdapter,
    OpenAlexOQLAdapter,
    CrossrefAdapter,
    EuropePMCAdapter,
    COREAdapter,
    ScopusAdapter,
    WebOfScienceStarterAdapter,
    WebOfScienceExpandedAdapter,
)
from .search import EvidenceSearch, MultiSearchResult
from .translators import Translation, TranslationDiagnostic, TranslationStatus, translate

from .scientific_benchmark import (
    AblationResult,
    BlockingRecallBenchmark,
    BlockingRecallResult,
    BootstrapCI,
    DeduplicationAblationBenchmark,
    MetadataStressBenchmark,
    QueryTranslationBenchmark,
    QueryTranslationBenchmarkCase,
    QueryTranslationBenchmarkResult,
    RetrievalSetMetrics,
    ScalabilityBenchmark,
    ScalabilityPoint,
    ScientificBenchmarkBundle,
    StressPoint,
    StudyLinkageAblationBenchmark,
    bootstrap_proportion_ci,
)

from .external_validation import (
    DedupPartitionBenchmark,
    DedupPartitionMetrics,
    ExternalDatasetSpecification,
    ExternalDatasetIntegrityCheck,
    ExternalDeduplicationResult,
    ExternalGoldDataset,
    ExternalRemovalGoldDataset,
    ExternalRemovalValidationResult,
    RemovalLabelMetrics,
    RemovalLabelBenchmark,
    RemovalRetentionComparison,
    load_external_dataset_specifications,
    load_external_gold_dataset,
    validate_external_dataset,
    PublishedDeduplicationBaseline,
    published_2026_baselines,
    write_external_validation_result,
    write_external_removal_validation_result,
    write_removal_retention_comparison,
    write_published_2026_baselines,
)
from .external_sources import (
    ASySD_OSF_NODE,
    ASySD_VALIDATION_FILENAMES,
    ExternalSourceFile,
    OSFPublicFileFetcher,
    fetch_asysd_validation_files,
)
from .external_runner import ExternalRunSummary, run_external_validation_plan

from .benchmark_data import (
    synthetic_deduplication_dataset,
    synthetic_study_linkage_dataset,
    synthetic_unique_records,
)

from .prisma import (
    PrismaAccountingError,
    PrismaBuilder,
    PrismaFlow,
    PrismaSearchContext,
    PrismaSearchReport,
    PrismaSearchSource,
    PrismaSSupportItem,
    write_prisma_bundle,
)

from .statistical_reporting import (
    ConfidenceInterval,
    DatasetRemovalStatistics,
    MacroMetric,
    RemovalStatisticalReport,
    load_blind_removal_metrics,
    summarize_removal_metrics,
    summarize_removal_result_directory,
    wilson_interval,
    write_removal_statistical_report,
)

__all__ = [
    "EvidenceRecord",
    "SourceHit",
    "QueryNode",
    "Term",
    "Phrase",
    "Boolean",
    "Not",
    "Field",
    "ControlledVocabulary",
    "Proximity",
    "SearchField",
    "SearchQuery",
    "QueryParser",
    "QuerySyntaxError",
    "parse_query",
    "render",
    "ConceptBlock",
    "PICOBuilder",
    "PECOBuilder",
    "Translation",
    "TranslationDiagnostic",
    "TranslationStatus",
    "translate",
    "DeduplicationEngine",
    "ConfidenceDeduplicationEngine",
    "DeduplicationDecision",
    "DeduplicationResult",
    "DeduplicationStats",
    "DuplicateLink",
    "EvidenceContribution",
    "MatchAssessment",
    "MatchFeatures",
    "LabeledPair",
    "BenchmarkMetrics",
    "ThresholdResult",
    "DeduplicationBenchmark",
    "PlattCalibrator",
    "DoubleCountingRisk",
    "PublicationRole",
    "StudyEvidenceContribution",
    "StudyFamily",
    "StudyLinkAssessment",
    "StudyLinkDecision",
    "StudyLinkFeatures",
    "StudyLinkageEngine",
    "StudyLinkageResult",
    "StudyLinkageStats",
    "classify_publication_role",
    "extract_registry_ids",
    "extract_study_acronyms",
    "StudyLabeledPair",
    "StudyLinkageBenchmark",
    "StudyLinkageMetrics",
    "StudyThresholdResult",
    "stable_record_id",
    "DEFAULT_EXCLUSION_REASONS",
    "ExclusionReason",
    "ReasonCodebook",
    "ScreeningConflict",
    "ScreeningDecision",
    "ScreeningEvent",
    "ScreeningLedger",
    "ScreeningStage",
    "ReviewerAgreement",
    "ImportResult",
    "ImportWarning",
    "read_csv",
    "read_ris",
    "record_to_row",
    "write_asreview_csv",
    "write_bibtex",
    "write_csv",
    "write_jsonl",
    "write_ris",
    "write_screening_bundle",
    "AblationResult",
    "BlockingRecallBenchmark",
    "BlockingRecallResult",
    "BootstrapCI",
    "DeduplicationAblationBenchmark",
    "MetadataStressBenchmark",
    "QueryTranslationBenchmark",
    "QueryTranslationBenchmarkCase",
    "QueryTranslationBenchmarkResult",
    "RetrievalSetMetrics",
    "ScalabilityBenchmark",
    "ScalabilityPoint",
    "ScientificBenchmarkBundle",
    "StressPoint",
    "StudyLinkageAblationBenchmark",
    "bootstrap_proportion_ci",
    "DedupPartitionBenchmark",
    "DedupPartitionMetrics",
    "ExternalDatasetSpecification",
    "ExternalDatasetIntegrityCheck",
    "ExternalDeduplicationResult",
    "ExternalGoldDataset",
    "ExternalRemovalGoldDataset",
    "ExternalRemovalValidationResult",
    "RemovalLabelMetrics",
    "RemovalLabelBenchmark",
    "RemovalRetentionComparison",
    "load_external_dataset_specifications",
    "load_external_gold_dataset",
    "validate_external_dataset",
    "PublishedDeduplicationBaseline",
    "published_2026_baselines",
    "write_external_validation_result",
    "write_external_removal_validation_result",
    "write_removal_retention_comparison",
    "write_published_2026_baselines",
    "ASySD_OSF_NODE",
    "ASySD_VALIDATION_FILENAMES",
    "ExternalSourceFile",
    "OSFPublicFileFetcher",
    "fetch_asysd_validation_files",
    "ExternalRunSummary",
    "run_external_validation_plan",
    "synthetic_deduplication_dataset",
    "synthetic_study_linkage_dataset",
    "synthetic_unique_records",
    "SearchManifest",
    "DiskResponseCache",
    "RawAuditStore",
    "RetryPolicy",
    "RequestLogEntry",
    "HTTPRequestError",
    "AdapterResult",
    "PubMedAdapter",
    "OpenAlexAdapter",
    "OpenAlexOQLAdapter",
    "CrossrefAdapter",
    "EuropePMCAdapter",
    "COREAdapter",
    "ScopusAdapter",
    "WebOfScienceStarterAdapter",
    "WebOfScienceExpandedAdapter",
    "EvidenceSearch",
    "MultiSearchResult",
    "PrismaAccountingError",
    "PrismaBuilder",
    "PrismaFlow",
    "PrismaSearchContext",
    "PrismaSearchReport",
    "PrismaSearchSource",
    "PrismaSSupportItem",
    "write_prisma_bundle",
    "ASySDPerformanceContract",
    "calculate_asysd_performance_contract",
    "EndNoteXMLGoldImport",
    "EndNoteXMLGoldReader",
    "EndNoteXMLImportStats",
    "load_endnote_xml_gold",
    "BELLER_ENDNOTE_REPOSITORY",
    "BELLER_ENDNOTE_COMMIT",
    "BELLER_ENDNOTE_FILES",
    "GitHubPinnedFileFetcher",
    "fetch_beller_endnote_validation_files",
    "verify_beller_endnote_validation_files",
    "ConfidenceInterval",
    "DatasetRemovalStatistics",
    "MacroMetric",
    "RemovalStatisticalReport",
    "load_blind_removal_metrics",
    "summarize_removal_metrics",
    "summarize_removal_result_directory",
    "wilson_interval",
    "write_removal_statistical_report",
    "ValidationLockCheck",
    "ValidationLockReport",
    "sha256_file",
    "verify_frozen_validation_lock",
    "write_validation_run_manifest",
]

from .asysd_compat import ASySDPerformanceContract, calculate_asysd_performance_contract



from .external_sources import (
    BELLER_ENDNOTE_REPOSITORY,
    BELLER_ENDNOTE_COMMIT,
    BELLER_ENDNOTE_FILES,
    GitHubPinnedFileFetcher,
    fetch_beller_endnote_validation_files,
    verify_beller_endnote_validation_files,
)

from .endnote_gold import (
    EndNoteXMLGoldImport,
    EndNoteXMLGoldReader,
    EndNoteXMLImportStats,
    load_endnote_xml_gold,
)

from .validation_provenance import write_validation_run_manifest

from .validation_lock import (
    ValidationLockCheck,
    ValidationLockReport,
    sha256_file,
    verify_frozen_validation_lock,
)

__version__ = "0.9.10.dev0"
